# _config.yml
title: atc-admin
description: admin panel for generator
theme: jekyll-theme-primer

# ВАЖЛИВО: виключаємо node_modules і все, що не має оброблятись
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - README.md
  - .github
